config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content,    length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(content: params[:post][:content])
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "ツイート投稿完了！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "ツイートを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "ツイートを削除しました"
  end

  def confirm
    @post = Post.new(post_params)
    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form"></div>
  <%= form_with(model: @post, local: true, url: choose_new_or_edit ) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>エラー</h2>
      </div>
    <% end %>
    <div class="post_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
  <% end %>

  <%= link_to "ブログ一覧画面にもどる", posts_path %>
</div>
<footer>
  <p>テスト</p>
</footer>

app/views/posts/confirm.html.erb
<header>
  <h1>テスト</h1>
</header>
<div class="form"></div>
  <h3>以下の内容で、送信する。</h3>

  <%= form_with(model: @post, local: true) do |form| %>
    <%= form.hidden_field :content %>

    <p>本文:<%= @post.content %></p>
    <%= form.submit  "投稿する" %>

    <%= form.submit "戻る", name: 'back' %>
<% end %>
</div>

<footer>
  <p>テスト</p>
</footer>

app/views/posts/edit.html.erb
<header>
  <h2>ツイートを作成する</h2>

</header>
  <%= render 'form' %>

app/views/posts/index.html.erb
<body>
  <header>
    <h1>Twitterクローン</h1>
  </header>
  <p class="notice"><%= notice %></p>
  <table>
    <tr>
      <th>Content</th>
    </tr>

    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>

        <td><%= link_to '詳細を確認する', post_path(post.id) %></td>
        <td><%= link_to "ツイートを編集する", edit_post_path(post.id), data: { confirm: '本当に編集していいですか？' } %></td>
        <td><%= link_to 'ツイートを削除する', post_path(post.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
      </tr>
    <% end %>
  </table>
  <div class = "new_button">
    <%= link_to '新しくツイートを投稿する', new_post_path %>
  </div>
  <footer>
    <p>テスト</p>
  </footer>
</body>

app/views/posts/new.html.erb
<header>
  <h2>ツイートを作成する</h2>
</header>
  <%= render 'form' %>

app/views/posts/show.html.erb
<header>
  <h1>ツイート詳細画面</h1>
</header>
<div class="form">
  <p>内容: <%= @post.content %></p>
  <%= link_to "ブログ一覧画面にもどる", posts_path %>
</div>
<footer>
  <p>テスト</p>
</footer>